# Домашнее задание

# Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
import numpy as np

In [4]:
N = int(input())
P = np.arange(0, N)
P = P[::-1]
P

10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [5]:
N = int(input())
matrix = np.diag(np.arange(N,0, -1))
summ=0
for line in matrix:
    for K in line:
        summ+=K
print('сумма: {}'.format(summ))

5
сумма: 15


# Задание 3

Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [6]:
from numpy import linalg

# коэффициенты при переменных в левой части уравнения
a = np.array( [ [4,2,1], [1,3,0], [0,5,4] ] )

# значения в правой части уравнения
b = np.array( [4, 12, -3] )

linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

# Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

Матрица в виде numpy array

In [7]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [8]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [9]:
users_stats, next_user_stats

(array([[2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]]),
 array([0, 1, 2, 0, 0, 0]))

In [16]:
def cosine( users_stats, next_user_stats ):
    """
    Подсчет косинуса угла между векторами users_stats, next_user_stats по их координатам
    """
    
    # длины векторов
    users_statsLength = np.linalg.norm( users_stats )
    next_user_statsLength = np.linalg.norm( next_user_stats )
    
    return np.dot( users_stats, next_user_stats ) / ( users_statsLength * next_user_statsLength )

In [17]:
cosine( users_stats, next_user_stats )

array([0.04688072, 0.23440362, 0.09376145, 0.23440362, 0.09376145,
       0.        , 0.        , 0.14064217, 0.        , 0.        ])

Откуда видно, что ближайшее к 1 значения у двух пользователей:
 Начиная с 0:
  2 и 4 строки наиболее похожие покупатели 
:)

In [32]:
cosine( users_stats, next_user_stats )[2]


0.09376144618769908

In [37]:
cosine( users_stats, next_user_stats )[4]

0.09376144618769908